version: '3'
services:
  master_postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
  url_shortener_postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5433:5432'
  master_redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      -  ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
    command: server --console-address :9001 /data
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 user password;
      /usr/bin/mc mb minio/corpbucket;
      /usr/bin/mc anonymous set public minio/corpbucket;
      exit 0;
      "
# Саша сказал что поддержку zookeeper могут прекратить, лучше kraft, Дима сказал что ничего не слышал об этот
  master_zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: master_zookeeper
    platform: linux/arm64
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
    ports:
      - "2181:2181"

  master_kafka:
    image: confluentinc/cp-kafka:latest
    container_name: master_kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "master_zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: |
        posts:1:1, 
        post_views:1:1, 
        likes:1:1, 
        comments:1:1, 
        posts_update_feeds:1:1, 
        post_views_update:1:1, 
        post_likes_update:1:1, 
        post_comments_update:1:1, 
        like_comment:1:1, 
        post_comment_likes_update:1:1, 
        profile_view:1:1,
        premium_bought:1:1,
        mentorship_request_received,
        mentorship_request_accepted,
        event_start,
        new_follower,
        user_ban
    ports:
      - "9092:9092"
    depends_on:
      - master_zookeeper
# Совет Димы kafka-tools, нашел Семен Offset Explorer (formerly Kafka Tool) is a GUI, Дима сказал что вроде это тоже оно
  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    environment:
      AKHQ_CONFIGURATION: |-
        akhq:
          connections:
            kafka-docker:
              properties:
                bootstrap.servers: "master_kafka:9092"
    ports:
      - "8088:8080"
    depends_on:
      - master_kafka